package cc.ibooker.daogenerator;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import cc.ibooker.daogenerator.User;
import cc.ibooker.daogenerator.Friend;

import cc.ibooker.daogenerator.UserDao;
import cc.ibooker.daogenerator.FriendDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig friendDaoConfig;

    private final UserDao userDao;
    private final FriendDao friendDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        friendDao = new FriendDao(friendDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Friend.class, friendDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        friendDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

}
